/** @type {import('tailwindcss').Config} */
export default {
  content: ['./app/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}', './lib/**/*.{js,ts,jsx,tsx}', './store/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: 'var(--background)',
        'background-deep': '#0F172A',
        surface: 'var(--surface)',
        'surface-dim': 'var(--surface)',
        'surface-bright': 'rgba(255, 255, 255, 0.12)',
        'surface-container-lowest': '#0B1020',
        'surface-container-low': 'var(--surface)',
        'surface-container': 'var(--surface)',
        'surface-container-high': 'rgba(255, 255, 255, 0.12)',
        'surface-container-highest': 'rgba(255, 255, 255, 0.15)',
        'on-surface': 'var(--foreground)',
        'on-surface-variant': 'var(--muted)',
        'inverse-surface': 'var(--foreground)',
        'inverse-on-surface': 'var(--background)',
        outline: 'var(--border)',
        'outline-variant': 'var(--border)',
        'surface-tint': 'var(--primary)',
        primary: 'var(--primary)',
        'on-primary': '#FFFFFF',
        'primary-container': 'rgba(108, 99, 255, 0.2)',
        'on-primary-container': 'var(--primary)',
        'inverse-primary': 'var(--primary)',
        secondary: 'var(--secondary)',
        'on-secondary': '#FFFFFF',
        'secondary-container': 'rgba(0, 212, 255, 0.2)',
        'on-secondary-container': 'var(--secondary)',
        tertiary: 'var(--tertiary)',
        'on-tertiary': '#FFFFFF',
        'tertiary-container': 'rgba(56, 189, 248, 0.2)',
        'on-tertiary-container': 'var(--tertiary)',
        error: 'var(--danger)',
        'on-error': '#FFFFFF',
        'error-container': 'var(--danger)',
        'on-error-container': '#FFFFFF',
        emerald: 'var(--success)',
        teal: 'var(--success)',
        'brand-deep': '#0F172A',
        success: 'var(--success)',
        danger: 'var(--danger)',
        muted: 'var(--muted)',
        warning: '#F59E0B',
      },
      spacing: {
        unit: '4px',
        'margin-main': '20px',
        'container-margin': '20px',
        'gutter-bento': '12px',
        gutter: '16px',
        'stack-gap': '16px',
        'card-padding': '24px',
        'section-padding': '24px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
      },
      fontFamily: {
        sans: ['Inter', 'Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        headline: ['Inter', 'Manrope', 'sans-serif'],
        mono: ['Geist', 'monospace'],
        'mono-data': ['Geist', 'monospace'],
        'label-caps': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'display-amount': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-balance': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'amount-md': ['18px', { lineHeight: '24px', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'mono-data': ['14px', { lineHeight: '20px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '0.75rem',
        md: '1rem',
        lg: '1.25rem',
        xl: '1.5rem',
        '2xl': '2rem',
        '28px': '28px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
