/** @type {import('tailwindcss').Config} */
export default {
  content: ['./app/**/*.{js,ts,jsx,tsx}', './components/**/*.{js,ts,jsx,tsx}', './lib/**/*.{js,ts,jsx,tsx}', './store/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#F5F7F8',
        'background-deep': '#EAF8F6',
        surface: '#FFFFFF',
        'surface-dim': '#F5F7F8',
        'surface-bright': '#FFFFFF',
        'surface-container-lowest': '#FFFFFF',
        'surface-container-low': '#F5F7F8',
        'surface-container': '#EAF8F6',
        'surface-container-high': '#FFFFFF',
        'surface-container-highest': '#FFFFFF',
        'on-surface': '#102A43',
        'on-surface-variant': '#6B7280',
        'inverse-surface': '#102A43',
        'inverse-on-surface': '#FFFFFF',
        outline: '#E5E7EB',
        'outline-variant': '#E5E7EB',
        'surface-tint': '#0F9D8A',
        primary: '#0F9D8A',
        'on-primary': '#FFFFFF',
        'primary-container': '#00BFA6',
        'on-primary-container': '#FFFFFF',
        'inverse-primary': '#0B6B61',
        secondary: '#00BFA6',
        'on-secondary': '#FFFFFF',
        'secondary-container': '#EAF8F6',
        'on-secondary-container': '#FFFFFF',
        tertiary: '#FFB77B',
        'on-tertiary': '#4D2700',
        'tertiary-container': '#D87802',
        'on-tertiary-container': '#432100',
        error: '#EF4444',
        'on-error': '#FFFFFF',
        'error-container': '#991B1B',
        'on-error-container': '#FFFFFF',
        // Standardized semantic color keys
        emerald: '#10B981',
        teal: '#0F9D8A',
        'brand-deep': '#102A43',
        success: '#10B981',
        danger: '#EF4444',
        muted: '#6B7280',
        warning: '#FFB77B',
      },
      spacing: {
        unit: '4px',
        'margin-main': '20px',
        'container-margin': '20px',
        'gutter-bento': '12px',
        gutter: '16px',
        'stack-gap': '16px',
        'card-padding': '24px',
        'section-padding': '24px',
        'stack-sm': '8px',
        'stack-md': '16px',
        'stack-lg': '32px',
      },
      fontFamily: {
        sans: ['Inter', 'Manrope', 'ui-sans-serif', 'system-ui', 'sans-serif'],
        headline: ['Inter', 'Manrope', 'sans-serif'],
        mono: ['Geist', 'monospace'],
        'mono-data': ['Geist', 'monospace'],
        'label-caps': ['Hanken Grotesk', 'sans-serif'],
      },
      fontSize: {
        'display-amount': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'display-balance': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '700' }],
        'headline-md': ['20px', { lineHeight: '28px', fontWeight: '600' }],
        'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['12px', { lineHeight: '16px', fontWeight: '400' }],
        'amount-md': ['18px', { lineHeight: '24px', fontWeight: '700' }],
        'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '600' }],
        'mono-data': ['14px', { lineHeight: '20px', fontWeight: '500' }],
      },
      borderRadius: {
        sm: '0.5rem',
        DEFAULT: '0.75rem',
        md: '1rem',
        lg: '1.25rem',
        xl: '1.5rem',
        '2xl': '2rem',
        '28px': '28px',
        full: '9999px',
      },
    },
  },
  plugins: [],
};
